version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: /Users/nmmert/development/chatbotproject/Dockerfile
    ports: 
      - "3000:80"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
    